namespace nilnul.dev.src
{
	/// <summary>
	/// div that is not any of:
	///		-) dotLed
	///		-) unlisted by settings in ancestor
	///		
	///		-) autogenerated
	/// </summary>
	interface ICraft:src.div_.IDelvable { }
}
