using nilnul.dev.src.div.dir_;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace nilnul.dev.src.div_
{

	/// <summary>
	/// each dir is <see cref="listable"/> as well as <see cref="notDotLed"/>
	/// also except last dir, each dir is nonneglected by the cfg within that dir; last dir's cfg would be checked later outer of this scope.
	/// 
	/// each dir is checked by its parent to ensure it's not autogenerated, by tools such as VisualStudio.
	/// 
	/// </summary>
	/// <remarks>
	/// note: for the folder where this div is parented, the folder itself is not checked whether it's listable or dotLed or autogenerted or neglected.
	///note:
	///		abc\asdfa-dad\asdfa
	///			is not delvable, but still work by gitRepo. it's just unable to be a repo module root.
	/// </remarks>
	/// alias:
	///		delvable
	///			similar to dev.
	///		modulable
	///			can be initiated to be a git module. but the cognomen of this can be empty
	///		raw
	///		work

	public interface IDelvable
		//:IWordsable
	{
	}
}
