using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace nilnul.dev.src.divisions_
{
	/// <summary>
	/// manually edited files. work of developers.
	/// </summary>
	/// alias:
	///		IRaw
	///		IWork
	///	vs ICfg
	///		configurations are usr options, not pushed to shared repo
	///	vs IAutogenerated
	///		autogen are generated code by tools, not users. It can be restored by <see cref="IArtifact"/>
	internal class IArtifact
	{
	}
}
