using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace nilnul.fs.folder_.deV_.raW_
{
	/// <summary>
	/// userGenerated resources;
	/// </summary>
	/// alias:
	///		ur, meaning your that represents user rather than this lib generated, corresponding with 'my' which is generated by the programmer.
	internal class IUr
	{
	}
}
