using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace nilnul.dev.src.prj._meta_.evt_
{

	internal class IPostBuild
	{
		/// <see cref="_meta_.aim_.VsVersionary"/>
		/// eg:
		///		versionary:
		///			the pkg:
		///				nilnul.dev._src_._LIB_.1.1.1.1+fx
		///			,would mean for framework such as 4.8.
		///		the versionary is generated by postbuild event, and the dll might be still in build mode even with  the "+fx"  build meta which would mean the aim is for fx.
		///		
		///			the pkg:
		///				nilnul.dev._src_._LIB_.1.1.1.1-sym+fx
		///			,would mean for framework such as 4.8.
		///		the versionary is generated by postbuild event, and the dll might be still in build mode even with the prebuild tag:"-sym". the "+fx"  build meta would mean the aim is for fx.

	}
}
